POST http://localhost:3000/user/signup
content-type: application/json

{
 "email": "asdasdasd@gmail.com",
 "password": "asdasasdd"

}


GET http://localhost:3000/user/1

PATCH http://localhost:3000/user/2

{
    "e"""
}